### ISSUE TITLE
Releases with sar files

### ISSUE THREAD

**Issue by ekrebs5** [hpi-swa-teaching/SWT18-Project-09#47]
As someone interested in PowerSqueak, I want the releases to have sar files in order to easier install them.

**Comment by MrModder** [comment]
@ekrebs5 
This change might be more difficult, than it seemed at first.
We currently need to use Metacellos preLoad feature to clean up some invalid state, which is present in most Squeak 5.1 images.
If we don't clean up this state, using the PSTextMorph will throw errors, because its font cannot be resized.
As far as we know, .sar files don't have the capability to run code when they are installed, so the user would have to do the cleanup manually, which we do not find acceptable.

We will keep you updated if we find a solution.

**Comment by ekrebs5** [comment]
I feel like a sar file would still help, at the moment one has download the zip file containing the code of the release and add that per filetree, or one has to download your repo and switch to the commit.

Some thoughts from @tom95 on your problem:
``` Smalltalk
ZipArchive new

    addString: 'MyCustom doIt' as: 'install/preamble';

    writeToFileNamed: 'mypackage.sar'
```
Maybe `install/postscript` instead of preamble

More info is in the class comment of SARInstaller

**Comment by MrModder** [comment]
install/postscript looks pretty much like what we need.
I will look into it and try to get a .sar file ready for the upcoming v0.3 release today.

**Comment by MrModder** [comment]
Solved: PowerSqueak comes in the form of a .sar file as of v0.3
